[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

via_ir = true

[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"

#[etherscan]
#testnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
